import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { useInventoryStore } from '@/src/store/inventory';
import { Card, IconButton, ScreenHeader } from '@/src/components/ui';
import { palette, spacing } from '@/src/theme/tokens';
export default function Compare(){const{id}=useLocalSearchParams<{id?:string}>();const products=useInventoryStore(s=>s.products);const base=products.find(p=>p.id===id)||products[0];const other=products.filter(p=>p.id!==base.id).sort((a,b)=>a.category===base.category?-1:b.category===base.category?1:0)[0];const rows=[['Marque',base.brand,other.brand],['Catégorie',base.category,other.category],['Couleur',base.color,other.color],['Matière',base.material,other.material],['Prix',`${base.price} €`,`${other.price} €`],['Stock',`${base.quantity} unités`,`${other.quantity} unités`]];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow="Comparaison visuelle" title="Comparer les produits" action={<IconButton name="close" accessibilityLabel="Fermer" onPress={()=>router.back()}/>}/><View style={s.products}>{[base,other].map(p=><View key={p.id} style={s.product}><Image source={p.image} style={s.image}/><Text style={s.name} numberOfLines={2}>{p.name}</Text><Text style={s.sku}>{p.sku}</Text></View>)}</View><Card style={{paddingVertical:5}}>{rows.map(([label,a,b],i)=><View key={label} style={[s.row,i>0&&s.line]}><Text style={s.label}>{label}</Text><Text style={s.value}>{a}</Text><Text style={s.value}>{b}</Text></View>)}</Card><Text style={s.note}>La similarité combine catégorie, attributs OCR et apparence visuelle. Les résultats restent stockés localement.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,maxWidth:650,width:'100%',alignSelf:'center'},products:{flexDirection:'row',gap:12,marginBottom:16},product:{flex:1},image:{width:'100%',height:150,borderRadius:20,backgroundColor:palette.line},name:{fontSize:13,fontWeight:'700',color:palette.ink,marginTop:10},sku:{fontSize:10,color:palette.muted,marginTop:3},row:{flexDirection:'row',alignItems:'center',minHeight:54},line:{borderTopWidth:1,borderTopColor:palette.line},label:{width:85,fontSize:11,color:palette.muted},value:{flex:1,fontSize:11,fontWeight:'600',color:palette.ink,paddingHorizontal:6},note:{fontSize:11,lineHeight:17,color:palette.muted,textAlign:'center',marginTop:18}});
