import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useInventoryStore } from '@/src/store/inventory';
import { Card, IconButton, PrimaryButton, ScreenHeader } from '@/src/components/ui';
import { notify } from '@/src/utils/feedback';
import { palette, spacing } from '@/src/theme/tokens';
const types=[['in','Entrée','arrow-down'],['out','Sortie','arrow-up'],['transfer','Transfert','swap-horizontal'],['audit','Audit','clipboard-outline']] as const;
export default function Movement(){const params=useLocalSearchParams<{productId?:string}>();const products=useInventoryStore(s=>s.products);const move=useInventoryStore(s=>s.moveStock);const[productId,setProductId]=useState(params.productId||products[0]?.id);const[type,setType]=useState<'in'|'out'|'transfer'|'audit'>('in');const[quantity,setQuantity]=useState('1');const[note,setNote]=useState('');const[to,setTo]=useState('Dépôt B · A01');const submit=()=>{const n=Number(quantity);if(!productId||!Number.isFinite(n)||n<=0)return notify('Saisissez une quantité valide.');move(productId,type,n,note,to);notify('Mouvement enregistré.');router.back()};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow="Opération de stock" title="Nouveau mouvement" action={<IconButton name="close" accessibilityLabel="Fermer" onPress={()=>router.back()}/>}/><Text style={s.label}>TYPE D’OPÉRATION</Text><View style={s.types}>{types.map(([v,l,icon])=><Pressable key={v} onPress={()=>setType(v)} style={[s.type,type===v&&s.typeOn]}><Ionicons name={icon} size={20} color={type===v?'white':palette.sage}/><Text style={[s.typeText,type===v&&{color:'white'}]}>{l}</Text></Pressable>)}</View><Text style={s.label}>PRODUIT</Text><Card style={{padding:8}}>{products.map((p,i)=><Pressable key={p.id} onPress={()=>setProductId(p.id)} style={[s.product,i>0&&s.line]}><View style={[s.radio,productId===p.id&&s.radioOn]}>{productId===p.id&&<View style={s.radioDot}/>}</View><View style={{flex:1}}><Text style={s.productName}>{p.name}</Text><Text style={s.productMeta}>{p.sku} · {p.quantity} unités</Text></View></Pressable>)}</Card><Text style={s.label}>QUANTITÉ</Text><View style={s.quantity}><Pressable onPress={()=>setQuantity(String(Math.max(1,Number(quantity||1)-1)))} style={s.qButton}><Ionicons name="remove" size={22}/></Pressable><TextInput value={quantity} onChangeText={setQuantity} keyboardType="number-pad" style={s.qInput}/><Pressable onPress={()=>setQuantity(String(Number(quantity||0)+1))} style={s.qButton}><Ionicons name="add" size={22}/></Pressable></View>{type==='transfer'&&<><Text style={s.label}>DESTINATION</Text><TextInput value={to} onChangeText={setTo} style={s.input}/></>}<Text style={s.label}>NOTE OPTIONNELLE</Text><TextInput value={note} onChangeText={setNote} placeholder="Motif, fournisseur, référence…" placeholderTextColor={palette.subtle} style={[s.input,{height:90,textAlignVertical:'top'}]} multiline/><PrimaryButton label="Enregistrer le mouvement" icon="checkmark" onPress={submit}/></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,paddingBottom:40,maxWidth:650,width:'100%',alignSelf:'center'},label:{fontSize:10,fontWeight:'800',letterSpacing:1.2,color:palette.muted,marginTop:20,marginBottom:9},types:{flexDirection:'row',gap:7},type:{flex:1,minHeight:74,borderRadius:17,backgroundColor:'white',borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center',gap:6},typeOn:{backgroundColor:palette.ink,borderColor:palette.ink},typeText:{fontSize:10,fontWeight:'700',color:palette.ink},product:{flexDirection:'row',alignItems:'center',gap:12,padding:10},line:{borderTopWidth:1,borderTopColor:palette.line},radio:{width:20,height:20,borderRadius:10,borderWidth:2,borderColor:palette.line,alignItems:'center',justifyContent:'center'},radioOn:{borderColor:palette.sage},radioDot:{width:10,height:10,borderRadius:5,backgroundColor:palette.sage},productName:{fontSize:13,fontWeight:'700',color:palette.ink},productMeta:{fontSize:10,color:palette.muted,marginTop:3},quantity:{flexDirection:'row',alignItems:'center',gap:8},qButton:{width:52,height:52,borderRadius:16,backgroundColor:'white',borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center'},qInput:{flex:1,height:52,borderRadius:16,backgroundColor:'white',borderWidth:1,borderColor:palette.line,textAlign:'center',fontSize:20,fontWeight:'800',color:palette.ink},input:{backgroundColor:'white',borderWidth:1,borderColor:palette.line,borderRadius:16,padding:15,fontSize:14,color:palette.ink,marginBottom:20}});
