import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useInventoryStore } from '@/src/store/inventory';
import { Card, IconButton, ScreenHeader } from '@/src/components/ui';
import { palette, spacing } from '@/src/theme/tokens';
export default function Notifications(){const products=useInventoryStore(s=>s.products);const alerts=products.filter(p=>p.status!=='healthy');return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow={`${alerts.length} alertes actives`} title="Centre d’alertes" action={<IconButton name="close" accessibilityLabel="Fermer" onPress={()=>router.back()}/>}/>{alerts.map(p=><Pressable key={p.id} onPress={()=>router.push(`/product/${p.id}`)}><Card style={s.alert}><View style={[s.icon,{backgroundColor:p.status==='out'?palette.redSoft:palette.amberSoft}]}><Ionicons name={p.status==='out'?'close-circle-outline':'warning-outline'} size={21} color={p.status==='out'?palette.red:palette.amber}/></View><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.meta}>{p.status==='out'?'Stock épuisé':`${p.quantity} unités · seuil ${p.minStock}`}</Text></View><Ionicons name="chevron-forward" size={18} color={palette.subtle}/></Card></Pressable>)}{alerts.length===0&&<View style={s.empty}><Ionicons name="checkmark-circle-outline" size={50} color={palette.sage}/><Text style={s.emptyTitle}>Tout est sous contrôle</Text><Text style={s.emptyText}>Aucune alerte de stock active.</Text></View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,gap:11,maxWidth:650,width:'100%',alignSelf:'center'},alert:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},name:{fontSize:13,fontWeight:'700',color:palette.ink},meta:{fontSize:11,color:palette.muted,marginTop:4},empty:{alignItems:'center',paddingVertical:80},emptyTitle:{fontSize:18,fontWeight:'700',color:palette.ink,marginTop:15},emptyText:{fontSize:13,color:palette.muted,marginTop:5}});
