import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import * as LocalAuthentication from 'expo-local-authentication';
import { Card, IconButton, Pill, ScreenHeader, SectionTitle } from '@/src/components/ui';
import { useInventoryStore } from '@/src/store/inventory';
import { exportInventory, importInventoryJson } from '@/src/services/files';
import { confirm, notify } from '@/src/utils/feedback';
import { palette, spacing } from '@/src/theme/tokens';

export default function Settings(){const products=useInventoryStore(s=>s.products);const movements=useInventoryStore(s=>s.movements);const preferences=useInventoryStore(s=>s.preferences);const update=useInventoryStore(s=>s.updatePreferences);const replace=useInventoryStore(s=>s.replaceProducts);const recordBackup=useInventoryStore(s=>s.recordBackup);const reset=useInventoryStore(s=>s.resetDemo);const[indexing,setIndexing]=useState(false);
 const doExport=async(format:'csv'|'json')=>{try{const file=await exportInventory(format,products,movements);notify(`${file} a été préparé.`);if(format==='json')recordBackup()}catch{notify('Impossible d’exporter les données.')}};
 const doImport=async()=>{try{const imported=await importInventoryJson();if(imported)confirm('Remplacer l’inventaire ?',`${imported.length} produits ont été trouvés dans le fichier.`,()=>{replace(imported);notify('Inventaire importé.')})}catch{notify('Le fichier sélectionné est invalide.')}};
 const biometric=async()=>{if(!preferences.biometric){const available=await LocalAuthentication.hasHardwareAsync();if(!available)return notify('La biométrie n’est pas disponible sur cet appareil.');const auth=await LocalAuthentication.authenticateAsync({promptMessage:'Activer le déverrouillage biométrique'});if(!auth.success)return;}update({biometric:!preferences.biometric});notify(!preferences.biometric?'Biométrie activée.':'Biométrie désactivée.')};
 const aiModel=()=>Alert.alert('Modèle d’image','Choisissez le modèle utilisé par le moteur local.',[{text:'MobileCLIP · rapide',onPress:()=>update({aiModel:'MobileCLIP'})},{text:'EfficientNet Lite · précis',onPress:()=>update({aiModel:'EfficientNet Lite'})},{text:'Annuler',style:'cancel'}]);
 const ocr=()=>Alert.alert('Langues OCR','Le moteur peut analyser plusieurs langues simultanément.',[{text:'Français · Anglais',onPress:()=>update({ocrLanguages:['Français','Anglais']})},{text:'Français · Anglais · Arabe',onPress:()=>update({ocrLanguages:['Français','Anglais','Arabe']})},{text:'Annuler',style:'cancel'}]);
 const reindex=()=>{setIndexing(true);setTimeout(()=>{setIndexing(false);notify(`${products.length} produits ont été réindexés.`)},900)};
 const row=(icon:keyof typeof Ionicons.glyphMap,title:string,sub:string,onPress:()=>void,right?:React.ReactNode)=><Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={s.row}><View style={s.rowIcon}><Ionicons name={icon} size={19} color={palette.sage}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{sub}</Text></View>{right??<Ionicons name="chevron-forward" size={18} color={palette.subtle}/>}</Pressable>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow="Espace de travail" title="Réglages" action={<IconButton name="close" accessibilityLabel="Fermer" onPress={()=>router.back()}/>}/><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>AM</Text></View><View style={{flex:1}}><Text style={s.profileName}>Alex Martin</Text><Text style={s.profileMeta}>Inventaire principal · Administrateur</Text></View><Pill label="Local" tone="green" icon="shield-checkmark-outline"/></View>
 <SectionTitle title="Données & sauvegarde"/><Card style={s.group}>{row('cloud-upload-outline','Sauvegarde locale',preferences.lastBackup?new Date(preferences.lastBackup).toLocaleString('fr-FR'):'Aucune sauvegarde',()=>doExport('json'))}{row('document-text-outline','Exporter en CSV',`${products.length} références`,()=>doExport('csv'))}{row('push-outline','Importer une sauvegarde','Fichier JSON Atelier Inventory',doImport)}{row('sync-outline','Sauvegarde automatique',preferences.autoBackup?'Activée':'Désactivée',()=>update({autoBackup:!preferences.autoBackup}),<Switch value={preferences.autoBackup} onValueChange={v=>update({autoBackup:v})} trackColor={{true:palette.sage}}/>)}</Card>
 <SectionTitle title="Intelligence locale"/><Card style={s.group}>{row('sparkles-outline','Modèle d’image',preferences.aiModel,aiModel)}{row('language-outline','Langues OCR',preferences.ocrLanguages.join(' · '),ocr)}{row('images-outline',indexing?'Indexation en cours…':'Reconstruire l’index visuel',`${products.length} produits`,reindex,indexing?<Text style={s.progress}>•••</Text>:undefined)}</Card>
 <SectionTitle title="Sécurité"/><Card style={s.group}>{row('finger-print-outline','Verrouillage biométrique',preferences.biometric?'Activé':'Désactivé',biometric,<Switch value={preferences.biometric} onValueChange={biometric} trackColor={{true:palette.sage}}/>)}{row('key-outline','Code PIN local',preferences.pinEnabled?'Configuré':'Non configuré',()=>router.push('/pin' as any))}</Card>
 <SectionTitle title="Maintenance"/><Card style={s.group}>{row('refresh-outline','Réinitialiser les données de démonstration','Restaure le catalogue initial',()=>confirm('Réinitialiser les données ?','Les mouvements et recherches seront effacés.',()=>{reset();notify('Données réinitialisées.')},true))}</Card><Text style={s.version}>Atelier Inventory · Expo SDK 56 · v1.0.0</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,paddingBottom:40,maxWidth:700,width:'100%',alignSelf:'center'},profile:{backgroundColor:palette.ink,borderRadius:24,padding:17,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:48,height:48,borderRadius:17,backgroundColor:'#34443B',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:15,fontWeight:'800',color:'white'},profileName:{fontSize:15,fontWeight:'700',color:'white'},profileMeta:{fontSize:10,color:'#AAB8B0',marginTop:4},group:{paddingVertical:4},row:{minHeight:70,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:4,borderBottomWidth:1,borderBottomColor:palette.line},rowIcon:{width:38,height:38,borderRadius:13,backgroundColor:palette.sageSoft,alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:13,fontWeight:'700',color:palette.ink},rowSub:{fontSize:10,color:palette.muted,marginTop:4},progress:{fontSize:16,fontWeight:'800',color:palette.sage},version:{textAlign:'center',fontSize:10,color:palette.subtle,marginTop:30}});
