import { ScrollView, StyleSheet, Switch, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Card, IconButton, Pill, ScreenHeader, SectionTitle } from '@/src/components/ui';
import { palette, spacing } from '@/src/theme/tokens';
const groups=[{title:'Données & sauvegarde',rows:[['cloud-upload-outline','Sauvegarde locale','Aujourd’hui, 09:42'],['download-outline','Exporter l’inventaire','CSV · JSON · Images'],['push-outline','Importer des données','CSV ou archive']]},{title:'Intelligence locale',rows:[['sparkles-outline','Modèles IA','MobileCLIP · 68 Mo'],['language-outline','Langues OCR','Français · Anglais · Arabe'],['images-outline','Index visuel','137 produits indexés']]},{title:'Stockage & sécurité',rows:[['server-outline','Stockage','1,8 Go utilisés'],['finger-print-outline','Verrouillage biométrique','Activé'],['key-outline','Code PIN local','Configuré']]}];
export default function Settings(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><ScreenHeader eyebrow="Espace de travail" title="Réglages" action={<IconButton name="close" onPress={()=>router.back()}/>}/><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>AM</Text></View><View style={{flex:1}}><Text style={s.profileName}>Alex Martin</Text><Text style={s.profileMeta}>Inventaire principal · Administrateur</Text></View><Pill label="Local" tone="green" icon="shield-checkmark-outline"/></View><SectionTitle title="Apparence"/><Card><View style={s.row}><View style={s.rowIcon}><Ionicons name="moon-outline" size={19} color={palette.sage}/></View><View style={{flex:1}}><Text style={s.rowTitle}>Mode sombre automatique</Text><Text style={s.rowSub}>Suit les réglages de l’appareil</Text></View><Switch value={false} trackColor={{true:palette.sage}}/></View></Card>{groups.map(g=><View key={g.title}><SectionTitle title={g.title}/><Card style={{paddingVertical:4}}>{g.rows.map(([icon,title,sub],i)=><Pressable key={title} style={[s.row,i>0&&s.line]}><View style={s.rowIcon}><Ionicons name={icon as any} size={19} color={palette.sage}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{sub}</Text></View><Ionicons name="chevron-forward" size={18} color={palette.subtle}/></Pressable>)}</Card></View>)}<Text style={s.version}>Atelier Inventory · Expo SDK 56 · v1.0.0</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,paddingBottom:40,maxWidth:700,width:'100%',alignSelf:'center'},profile:{backgroundColor:palette.ink,borderRadius:24,padding:17,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:48,height:48,borderRadius:17,backgroundColor:'#34443B',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:15,fontWeight:'800',color:'white'},profileName:{fontSize:15,fontWeight:'700',color:'white'},profileMeta:{fontSize:10,color:'#AAB8B0',marginTop:4},row:{minHeight:68,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:4},line:{borderTopWidth:1,borderTopColor:palette.line},rowIcon:{width:38,height:38,borderRadius:13,backgroundColor:palette.sageSoft,alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:13,fontWeight:'700',color:palette.ink},rowSub:{fontSize:10,color:palette.muted,marginTop:4},version:{textAlign:'center',fontSize:10,color:palette.subtle,marginTop:30}});
