import { ScrollView, StyleSheet, Text, View, Pressable, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useInventoryStore } from '@/src/store/inventory';
import { Card, HeroGlow, IconButton, Pill, Progress, ScreenHeader, SectionTitle } from '@/src/components/ui';
import { ProductCard } from '@/src/components/ProductCard';
import { palette, spacing } from '@/src/theme/tokens';

export default function Dashboard(){
 const products=useInventoryStore(s=>s.products); const {width}=useWindowDimensions(); const total=products.reduce((a,p)=>a+p.quantity,0); const low=products.filter(p=>p.status!=='healthy').length; const value=products.reduce((a,p)=>a+p.quantity*p.price,0);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={[s.page,{maxWidth:width>800?1120:680}]} showsVerticalScrollIndicator={false}>
  <ScreenHeader eyebrow="Lundi · 22 juin" title="Bonjour, Alex" action={<View style={s.actions}><IconButton name="notifications-outline"/><IconButton name="person-outline" onPress={()=>router.push('/settings')}/></View>}/>
  <HeroGlow><View style={s.heroTop}><View><Text style={s.heroLabel}>VALEUR DE L’INVENTAIRE</Text><Text style={s.heroValue}>{value.toLocaleString('fr-FR')} €</Text><Text style={s.heroDelta}>↗ 8,4% ce mois-ci</Text></View><View style={s.heroIcon}><Ionicons name="layers-outline" size={25} color="#B8D2C0"/></View></View>
   <View style={s.metrics}><View><Text style={s.metricVal}>{total}</Text><Text style={s.metricLab}>Unités</Text></View><View style={s.divider}/><View><Text style={s.metricVal}>{products.length}</Text><Text style={s.metricLab}>Références</Text></View><View style={s.divider}/><View><Text style={[s.metricVal,{color:'#F2C17F'}]}>{low}</Text><Text style={s.metricLab}>Alertes</Text></View></View>
  </HeroGlow>
  <SectionTitle title="Actions rapides"/><View style={s.quickRow}>{[['scan','Scanner','Nouveau produit'],['swap-horizontal','Mouvement','Entrée · sortie'],['image','Recherche visuelle','Par image']].map(([icon,title,sub],i)=><Pressable key={title} onPress={()=>router.push(i===0?'/scan':i===2?'/search':'/inventory')} style={s.quick}><View style={s.quickIcon}><Ionicons name={icon as any} size={21} color={palette.sage}/></View><Text style={s.quickTitle}>{title}</Text><Text style={s.quickSub}>{sub}</Text></Pressable>)}</View>
  <SectionTitle title="Attention requise" action="Voir tout" onPress={()=>router.push('/inventory')}/><Card><View style={s.alertHead}><View><Text style={s.alertTitle}>Stock à surveiller</Text><Text style={s.alertSub}>{low} références sous le seuil</Text></View><Pill label="Action requise" tone="amber" icon="warning-outline"/></View><Progress value={67} color={palette.amber}/><View style={s.alertFoot}><Text style={s.alertFootText}>Niveau global des stocks</Text><Text style={s.alertFootValue}>67%</Text></View></Card>
  <SectionTitle title="Dernières mises à jour" action="Inventaire" onPress={()=>router.push('/inventory')}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</ScrollView>
  <View style={{height:30}}/>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{width:'100%',alignSelf:'center',padding:spacing.lg},actions:{flexDirection:'row',gap:8},heroTop:{flexDirection:'row',justifyContent:'space-between'},heroLabel:{fontSize:10,fontWeight:'700',letterSpacing:1.5,color:'#93A49B'},heroValue:{fontSize:34,fontWeight:'700',letterSpacing:-1.1,color:'white',marginTop:8},heroDelta:{fontSize:12,color:'#9BC4A7',fontWeight:'700',marginTop:7},heroIcon:{width:52,height:52,borderRadius:18,backgroundColor:'#293831',alignItems:'center',justifyContent:'center'},metrics:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:26,paddingTop:18,borderTopWidth:1,borderTopColor:'#304039'},metricVal:{fontSize:20,fontWeight:'700',color:'white'},metricLab:{fontSize:11,color:'#93A49B',marginTop:3},divider:{width:1,height:33,backgroundColor:'#304039'},quickRow:{flexDirection:'row',gap:10},quick:{flex:1,backgroundColor:'white',borderRadius:20,padding:14,borderWidth:1,borderColor:palette.line,minHeight:132},quickIcon:{width:38,height:38,borderRadius:13,backgroundColor:palette.sageSoft,alignItems:'center',justifyContent:'center',marginBottom:14},quickTitle:{fontSize:13,fontWeight:'700',color:palette.ink},quickSub:{fontSize:10,color:palette.muted,marginTop:4},alertHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:18},alertTitle:{fontSize:15,fontWeight:'700',color:palette.ink},alertSub:{fontSize:11,color:palette.muted,marginTop:5},alertFoot:{flexDirection:'row',justifyContent:'space-between',marginTop:10},alertFootText:{fontSize:11,color:palette.muted},alertFootValue:{fontSize:11,fontWeight:'700',color:palette.ink}});
