import { useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useInventoryStore } from '@/src/store/inventory';
import { ProductCard } from '@/src/components/ProductCard';
import { SearchBar } from '@/src/components/SearchBar';
import { IconButton, ScreenHeader } from '@/src/components/ui';
import { searchProducts } from '@/src/services/search';
import { palette, spacing } from '@/src/theme/tokens';
const filters=['Tous','Stock faible','Épuisé','Favoris'];
export default function Inventory(){const products=useInventoryStore(s=>s.products);const[q,setQ]=useState('');const[filter,setFilter]=useState('Tous');const result=useMemo(()=>searchProducts(products,q).filter(p=>filter==='Tous'||filter==='Stock faible'&&p.status==='low'||filter==='Épuisé'&&p.status==='out'||filter==='Favoris'&&p.favorite),[products,q,filter]);return <SafeAreaView style={s.safe}><FlatList data={result} keyExtractor={p=>p.id} renderItem={({item})=><ProductCard product={item} compact/>} ItemSeparatorComponent={()=><View style={{height:12}}/>} contentContainerStyle={s.page} ListHeaderComponent={<><ScreenHeader eyebrow={`${products.length} références · ${products.reduce((a,p)=>a+p.quantity,0)} unités`} title="Inventaire" action={<IconButton name="options-outline"/>}/><SearchBar value={q} onChangeText={setQ}/><View style={s.filters}>{filters.map(f=><Pressable key={f} onPress={()=>setFilter(f)} style={[s.filter,filter===f&&s.filterOn]}><Text style={[s.filterText,filter===f&&s.filterTextOn]}>{f}</Text></Pressable>)}</View><View style={s.resultHead}><Text style={s.resultText}>{result.length} produits</Text><Pressable style={s.sort}><Ionicons name="swap-vertical" size={14} color={palette.muted}/><Text style={s.sortText}>Récents</Text></Pressable></View></>} ListEmptyComponent={<View style={s.empty}><Ionicons name="cube-outline" size={42} color={palette.subtle}/><Text style={s.emptyTitle}>Aucun produit trouvé</Text><Text style={s.emptyText}>Essayez un autre terme ou retirez un filtre.</Text></View>} /></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,paddingBottom:100,maxWidth:700,width:'100%',alignSelf:'center'},filters:{flexDirection:'row',gap:8,marginTop:14,marginBottom:20,flexWrap:'wrap'},filter:{paddingHorizontal:14,paddingVertical:9,borderRadius:99,backgroundColor:'white',borderWidth:1,borderColor:palette.line},filterOn:{backgroundColor:palette.ink,borderColor:palette.ink},filterText:{fontSize:12,fontWeight:'600',color:palette.muted},filterTextOn:{color:'white'},resultHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},resultText:{fontSize:13,fontWeight:'700',color:palette.ink},sort:{flexDirection:'row',alignItems:'center',gap:4},sortText:{fontSize:12,color:palette.muted},empty:{alignItems:'center',padding:60},emptyTitle:{fontSize:17,fontWeight:'700',color:palette.ink,marginTop:15},emptyText:{fontSize:13,color:palette.muted,marginTop:7,textAlign:'center'}});
