import { useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import { runProductPipeline } from '@/src/ai/pipeline';
import { palette } from '@/src/theme/tokens';

export default function Scan(){const ref=useRef<CameraView>(null);const[permission,request]=useCameraPermissions();const[mode,setMode]=useState<'Produit'|'Code-barres'|'Lot'>('Produit');const[busy,setBusy]=useState(false);const snap=async()=>{if(!ref.current||busy)return;setBusy(true);Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);try{const photo=await ref.current.takePictureAsync({quality:.72,skipProcessing:false});if(photo){await runProductPipeline(photo.uri);router.push('/product/1?scanned=1');}}finally{setBusy(false)}};
 if(!permission?.granted)return <SafeAreaView style={s.permission}><View style={s.permissionIcon}><Ionicons name="camera-outline" size={30} color={palette.sage}/></View><Text style={s.permissionTitle}>Accès à la caméra</Text><Text style={s.permissionText}>La caméra est utilisée pour reconnaître les produits et lire leurs étiquettes. Les images restent sur cet appareil.</Text><Pressable onPress={request} style={s.allow}><Text style={s.allowText}>Autoriser la caméra</Text></Pressable></SafeAreaView>;
 return <View style={s.root}><CameraView ref={ref} style={StyleSheet.absoluteFill} facing="back" barcodeScannerSettings={{barcodeTypes:['ean13','ean8','qr','code128']}}/><View style={s.shade}/><SafeAreaView style={s.overlay}><View style={s.top}><Pressable style={s.circle} onPress={()=>router.back()}><Ionicons name="close" size={22} color="white"/></Pressable><Text style={s.title}>Scanner un produit</Text><Pressable style={s.circle}><Ionicons name="flash-outline" size={22} color="white"/></Pressable></View><View style={s.modes}>{(['Produit','Code-barres','Lot'] as const).map(m=><Pressable onPress={()=>setMode(m)} key={m} style={[s.mode,mode===m&&s.modeOn]}><Text style={[s.modeText,mode===m&&s.modeTextOn]}>{m}</Text></Pressable>)}</View><View style={s.guide}><View style={[s.corner,s.tl]}/><View style={[s.corner,s.tr]}/><View style={[s.corner,s.bl]}/><View style={[s.corner,s.br]}/><View style={s.detect}><View style={s.dot}/><Text style={s.detectText}>Étiquette détectée</Text></View></View><Text style={s.help}>Cadrez l’étiquette ou l’emballage entier</Text><View style={s.features}><Text style={s.feature}>OCR multilingue</Text><View style={s.sep}/><Text style={s.feature}>Reconnaissance locale</Text></View><View style={s.bottom}><Pressable style={s.gallery}><Ionicons name="images-outline" size={24} color="white"/></Pressable><Pressable style={s.shutter} onPress={snap}><View style={s.shutterInner}>{busy&&<ActivityIndicator color={palette.ink}/>}</View></Pressable><Pressable style={s.gallery}><Ionicons name="layers-outline" size={24} color="white"/></Pressable></View></SafeAreaView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#101411'},shade:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'#00000025'},overlay:{flex:1,paddingHorizontal:22},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},circle:{width:44,height:44,borderRadius:15,backgroundColor:'#0B100D88',alignItems:'center',justifyContent:'center'},title:{fontSize:16,fontWeight:'700',color:'white'},modes:{alignSelf:'center',marginTop:24,backgroundColor:'#0B100DAA',borderRadius:16,padding:4,flexDirection:'row'},mode:{paddingHorizontal:15,paddingVertical:9,borderRadius:12},modeOn:{backgroundColor:'white'},modeText:{fontSize:12,fontWeight:'600',color:'#D4DBD6'},modeTextOn:{color:palette.ink},guide:{width:'88%',aspectRatio:.79,alignSelf:'center',marginTop:42,position:'relative',justifyContent:'flex-end',alignItems:'center',paddingBottom:18},corner:{position:'absolute',width:42,height:42,borderColor:'white'},tl:{top:0,left:0,borderTopWidth:3,borderLeftWidth:3,borderTopLeftRadius:19},tr:{top:0,right:0,borderTopWidth:3,borderRightWidth:3,borderTopRightRadius:19},bl:{bottom:0,left:0,borderBottomWidth:3,borderLeftWidth:3,borderBottomLeftRadius:19},br:{bottom:0,right:0,borderBottomWidth:3,borderRightWidth:3,borderBottomRightRadius:19},detect:{flexDirection:'row',alignItems:'center',gap:7,backgroundColor:'#18221DDD',paddingHorizontal:12,paddingVertical:7,borderRadius:99},dot:{width:7,height:7,borderRadius:5,backgroundColor:'#7FCC96'},detectText:{fontSize:11,fontWeight:'700',color:'white'},help:{textAlign:'center',fontSize:13,color:'white',fontWeight:'600',marginTop:20},features:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:10,marginTop:8},feature:{fontSize:10,color:'#D7DED9'},sep:{width:3,height:3,borderRadius:2,backgroundColor:'#9BA69F'},bottom:{marginTop:'auto',marginBottom:25,flexDirection:'row',alignItems:'center',justifyContent:'space-around'},gallery:{width:48,height:48,borderRadius:16,backgroundColor:'#0B100DAA',alignItems:'center',justifyContent:'center'},shutter:{width:80,height:80,borderRadius:40,borderWidth:3,borderColor:'white',alignItems:'center',justifyContent:'center'},shutterInner:{width:64,height:64,borderRadius:32,backgroundColor:'white',alignItems:'center',justifyContent:'center'},permission:{flex:1,backgroundColor:palette.paper,alignItems:'center',justifyContent:'center',padding:34},permissionIcon:{width:68,height:68,borderRadius:24,backgroundColor:palette.sageSoft,alignItems:'center',justifyContent:'center'},permissionTitle:{fontSize:23,fontWeight:'700',color:palette.ink,marginTop:20},permissionText:{fontSize:14,lineHeight:21,textAlign:'center',color:palette.muted,marginTop:10,maxWidth:360},allow:{backgroundColor:palette.ink,borderRadius:16,paddingHorizontal:24,paddingVertical:15,marginTop:24},allowText:{fontWeight:'700',color:'white'}});
