import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { SearchBar } from '@/src/components/SearchBar';
import { ProductCard } from '@/src/components/ProductCard';
import { Pill, ScreenHeader, SectionTitle } from '@/src/components/ui';
import { useInventoryStore } from '@/src/store/inventory';
import { searchProducts } from '@/src/services/search';
import { palette, spacing } from '@/src/theme/tokens';
export default function Search(){const products=useInventoryStore(s=>s.products);const recent=useInventoryStore(s=>s.recentSearches);const addRecent=useInventoryStore(s=>s.addRecentSearch);const clearRecent=useInventoryStore(s=>s.clearRecentSearches);const[q,setQ]=useState('');const[visual,setVisual]=useState(false);const result=useMemo(()=>visual?products.map((p,i)=>({...p,similarity:Math.max(.58,.96-i*.055)})).sort((a,b)=>(b.similarity||0)-(a.similarity||0)):searchProducts(products,q),[products,q,visual]);const update=(v:string)=>{setVisual(false);setQ(v)};const chooseImage=async()=>{const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.65});if(!picked.canceled){setQ('');setVisual(true)}};const submit=()=>{if(q.trim())addRecent(q)};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><ScreenHeader eyebrow="Texte · image · code-barres" title="Recherche intelligente"/><SearchBar value={q} onChangeText={update} onSubmit={submit} onCamera={chooseImage}/><Pressable onPress={chooseImage} style={s.visual}><View style={s.visualIcon}><Ionicons name="images-outline" size={25} color="white"/></View><View style={{flex:1}}><Text style={s.visualTitle}>Rechercher avec une image</Text><Text style={s.visualText}>Choisissez une photo pour classer les produits visuellement similaires.</Text></View><Ionicons name="chevron-forward" size={20} color="#9CB0A3"/></Pressable>{q||visual?<><SectionTitle title={visual?`${result.length} correspondances visuelles`:`${result.length} résultats`} action={visual?'Fermer':undefined} onPress={()=>setVisual(false)}/>{result.map(p=><View key={p.id} style={{marginBottom:12}}><ProductCard product={p} compact/></View>)}</>:<><SectionTitle title="Recherches récentes" action={recent.length?'Effacer':undefined} onPress={clearRecent}/><View style={s.chips}>{recent.length?recent.map(x=><Pressable key={x} onPress={()=>{setQ(x);addRecent(x)}}><Pill label={x} icon="time-outline"/></Pressable>):<Text style={s.none}>Aucune recherche récente</Text>}</View><SectionTitle title="Explorer par catégorie"/><View style={s.categories}>{[['Électroménager','flash-outline'],['Cuisine','restaurant-outline'],['Déco','color-palette-outline'],['Vaisselle','cafe-outline']].map(([name,icon])=><Pressable key={name} onPress={()=>{setQ(name);addRecent(name)}} style={s.category}><View style={s.categoryIcon}><Ionicons name={icon as any} size={20} color={palette.sage}/></View><Text style={s.categoryName}>{name}</Text><Text style={s.categoryCount}>{products.filter(p=>p.category===name).length} réf.</Text></Pressable>)}</View><SectionTitle title="Suggestions visuelles"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{products.slice(2,6).map((p,i)=><ProductCard key={p.id} product={{...p,similarity:.96-i*.04}}/>)}</ScrollView></>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,paddingBottom:110,maxWidth:700,width:'100%',alignSelf:'center'},visual:{marginTop:14,padding:16,borderRadius:22,backgroundColor:palette.ink,flexDirection:'row',alignItems:'center',gap:13},visualIcon:{width:48,height:48,borderRadius:16,backgroundColor:'#314139',alignItems:'center',justifyContent:'center'},visualTitle:{fontSize:14,fontWeight:'700',color:'white'},visualText:{fontSize:11,lineHeight:16,color:'#A9B8AF',marginTop:4},chips:{flexDirection:'row',gap:8,flexWrap:'wrap'},none:{fontSize:12,color:palette.muted},categories:{flexDirection:'row',flexWrap:'wrap',gap:10},category:{width:'48%',backgroundColor:'white',padding:15,borderRadius:20,borderWidth:1,borderColor:palette.line},categoryIcon:{width:38,height:38,borderRadius:13,backgroundColor:palette.sageSoft,alignItems:'center',justifyContent:'center'},categoryName:{fontSize:13,fontWeight:'700',color:palette.ink,marginTop:14},categoryCount:{fontSize:11,color:palette.muted,marginTop:4}});
