import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { useInventoryStore } from '@/src/store/inventory';
import { IconButton, PrimaryButton, ScreenHeader } from '@/src/components/ui';
import { notify } from '@/src/utils/feedback';
import { palette, spacing } from '@/src/theme/tokens';
export default function EditProduct(){const{id}=useLocalSearchParams<{id:string}>();const product=useInventoryStore(s=>s.products.find(p=>p.id===id));const update=useInventoryStore(s=>s.updateProduct);const[form,setForm]=useState(product||useInventoryStore.getState().products[0]);if(!product)return null;const field=(key:keyof typeof form,label:string,keyboardType?:'numeric'|'default')=><><Text style={s.label}>{label}</Text><TextInput value={String(form[key]??'')} onChangeText={v=>setForm({...form,[key]:keyboardType==='numeric'?Number(v||0):v})} keyboardType={keyboardType} style={s.input}/></>;const save=()=>{if(!form.name.trim()||!form.sku.trim())return notify('Le nom et le SKU sont obligatoires.');update(product.id,form);notify('Produit mis à jour.');router.back()};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><ScreenHeader eyebrow={product.sku} title="Modifier le produit" action={<IconButton name="close" accessibilityLabel="Fermer" onPress={()=>router.back()}/>}/>{field('name','NOM DU PRODUIT')}{field('brand','MARQUE')}{field('sku','SKU / RÉFÉRENCE')}{field('barcode','CODE-BARRES')}{field('category','CATÉGORIE')}{field('color','COULEUR')}{field('material','MATIÈRE')}{field('location','EMPLACEMENT')}{field('quantity','QUANTITÉ','numeric')}{field('minStock','SEUIL MINIMUM','numeric')}{field('price','PRIX UNITAIRE (€)','numeric')}<PrimaryButton label="Enregistrer les modifications" icon="checkmark" onPress={save}/></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.paper},page:{padding:spacing.lg,paddingBottom:45,maxWidth:620,width:'100%',alignSelf:'center'},label:{fontSize:10,fontWeight:'800',letterSpacing:1.1,color:palette.muted,marginTop:14,marginBottom:7},input:{height:51,backgroundColor:'white',borderWidth:1,borderColor:palette.line,borderRadius:16,paddingHorizontal:15,fontSize:14,color:palette.ink,marginBottom:2}});
